apiVersion: v1
kind: Service
metadata:
  name: spring-{{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: spring-{{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-{{ .Release.Name }}
  labels:
    app: spring-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: spring-{{ .Release.Name }}
  replicas: {{ .Values.spring.replicas }}
  template:
    metadata:
      labels:
        app: spring-{{ .Release.Name }}
    spec:
      containers:
        - name: spring-{{ .Release.Name }}
          image: {{ .Values.spring.docker.repository }}/{{ .Values.spring.docker.image }}:{{ .Values.spring.docker.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: {{ .Values.spring.healthcheckEndpoint }}
              port: 8080
              httpHeaders:
                - name: Content-Type
                  value: application/json
            initialDelaySeconds: 10
            periodSeconds: 15

